GET http://localhost:3005/restaurants


####

GET http://localhost:3005/restaurants/2

###

POST http://localhost:3005/restaurants
Content-Type: application/json

{
    "name":"check", 
    "chef_id":1,
    "popular":false,
    "signuture_dish_id":1,
    "dishes_id":[1,2],
    "src": "claro.png"
}

###

GET http://localhost:3005/dishes


####

GET http://localhost:3005/restaurants/2

###

GET http://localhost:3005/restaurants


####

GET http://localhost:3005/restaurants/2

###

GET http://localhost:3005/auth/user
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImEiLCJpYXQiOjE2NDM5MjY0NzMsImV4cCI6MTY0MzkyNjUwOH0.eeIOc9z5xyev89udsTVCx0WEfGsYU7Vvs6Voo8oR79s

###

POST http://localhost:4000/token
Content-Type: application/json

{
    token: 
}

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    token: 
}
###

POST http://localhost:4000/login
Content-Type: application/json

{
    "email":"a"
}
